services:
  db:
    image: postgres:16-alpine
    container_name: flashcardsinspace-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: flashcardsinspace
      POSTGRES_USER: fins
      POSTGRES_PASSWORD: fins
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashcardsinspace -d flashcardsinspace"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flashcardsinspace-app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker,dev
      APP_PORT: 8442
      APP_DATASOURCE_URL: jdbc:postgresql://db:5432/flashcardsinspace
      APP_DATASOURCE_USERNAME: fins
      APP_DATASOURCE_PASSWORD: fins
      APP_SECURITY_JWT_SECRET: VOyWwmqaktRJ0PHYs6q3FBHrcuBwkacf02akxwqemoySEYxwkLceALCAQrmInkjAU3v12T1x5L6xBSwPlTD87g==
      APP_MAIL_ENABLED: false
    volumes:
      - ./props:/app/config:ro
    command: ["--spring.config.additional-location=file:/app/config/"]
    ports:
      - "8442:8442"

volumes:
  db_data:
